
WITH vendas AS (
    SELECT
        ID,
        ID_CLIENT,
        TRY_TO_NUMBER(ID_PRODUCT) AS ID_PRODUCT,
        TRY_TO_NUMBER(QTD) AS QTD,
        TRY_TO_DECIMAL(TOTAL, 38, 2) AS TOTAL_BRL,
        TRY_TO_DATE(C6) AS DATA_VENDA
    FROM LH_NAUTICALS.QUESTAO4.VENDAS_REAL
    WHERE TRY_TO_NUMBER(ID_PRODUCT) IS NOT NULL
),

custos AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        START_DATE AS DATA_INICIO_CUSTO,
        USD_PRICE
    FROM LH_NAUTICALS.QUESTAO4.CUSTOS_IMPORTACAO_TRATADOS
),

cambio AS (
    SELECT
        TO_DATE(data_cambio) AS DATA_CAMBIO,
        cotacao_venda
    FROM LH_NAUTICALS.QUESTAO4.CAMBIO_BCB_DOLL_BR
),

venda_custo AS (
    SELECT
        v.ID,
        v.ID_PRODUCT,
        v.QTD,
        v.TOTAL_BRL AS RECEITA_TOTAL_BRL,
        v.DATA_VENDA,
        c.PRODUCT_NAME,
        c.CATEGORY,
        c.DATA_INICIO_CUSTO,
        c.USD_PRICE,
        ROW_NUMBER() OVER (
            PARTITION BY v.ID
            ORDER BY c.DATA_INICIO_CUSTO DESC
        ) AS RN
    FROM vendas v
    JOIN custos c
        ON v.ID_PRODUCT = c.PRODUCT_ID
       AND c.DATA_INICIO_CUSTO <= v.DATA_VENDA
),

base AS (
    SELECT
        vc.ID,
        vc.ID_PRODUCT,
        vc.PRODUCT_NAME,
        vc.CATEGORY,
        vc.RECEITA_TOTAL_BRL,
        (vc.QTD * vc.USD_PRICE * cb.cotacao_venda) AS CUSTO_TOTAL_BRL
    FROM venda_custo vc
    JOIN cambio cb
        ON vc.DATA_VENDA = cb.DATA_CAMBIO
    WHERE vc.RN = 1
),

prejuizo_transacoes AS (
    SELECT
        ID_PRODUCT,
        PRODUCT_NAME,
        CATEGORY,
        RECEITA_TOTAL_BRL,
        CASE
            WHEN RECEITA_TOTAL_BRL < CUSTO_TOTAL_BRL THEN CUSTO_TOTAL_BRL - RECEITA_TOTAL_BRL
            ELSE 0
        END AS PREJUIZO_BRL
    FROM base
)

SELECT
    ID_PRODUCT,
    PRODUCT_NAME,
    CATEGORY,
    SUM(RECEITA_TOTAL_BRL) AS RECEITA_TOTAL_BRL,
    SUM(PREJUIZO_BRL) AS PREJUIZO_TOTAL_BRL,
    CASE
        WHEN SUM(RECEITA_TOTAL_BRL) = 0 THEN 0
        ELSE SUM(PREJUIZO_BRL) / SUM(RECEITA_TOTAL_BRL)
    END AS PERCENTUAL_PERDA
FROM prejuizo_transacoes
GROUP BY ID_PRODUCT, PRODUCT_NAME, CATEGORY
ORDER BY PREJUIZO_TOTAL_BRL DESC;


-- CRIAR A VIEW PARA TAREFA 2
CREATE OR REPLACE VIEW LH_NAUTICALS.QUESTAO4.VW_PREJUIZO_PRODUTO AS
WITH vendas AS (
    SELECT
        ID,
        ID_CLIENT,
        TRY_TO_NUMBER(ID_PRODUCT) AS ID_PRODUCT,
        TRY_TO_NUMBER(QTD) AS QTD,
        TRY_TO_DECIMAL(TOTAL, 38, 2) AS TOTAL_BRL,
        TRY_TO_DATE(C6) AS DATA_VENDA
    FROM LH_NAUTICALS.QUESTAO4.VENDAS_REAL
    WHERE TRY_TO_NUMBER(ID_PRODUCT) IS NOT NULL
),

custos AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        START_DATE AS DATA_INICIO_CUSTO,
        USD_PRICE
    FROM LH_NAUTICALS.QUESTAO4.CUSTOS_IMPORTACAO_TRATADOS
),

cambio AS (
    SELECT
        TO_DATE(data_cambio) AS DATA_CAMBIO,
        cotacao_venda
    FROM LH_NAUTICALS.QUESTAO4.CAMBIO_BCB_DOLL_BR
),

venda_custo AS (
    SELECT
        v.ID,
        v.ID_PRODUCT,
        v.QTD,
        v.TOTAL_BRL AS RECEITA_TOTAL_BRL,
        v.DATA_VENDA,
        c.PRODUCT_NAME,
        c.CATEGORY,
        c.DATA_INICIO_CUSTO,
        c.USD_PRICE,
        ROW_NUMBER() OVER (
            PARTITION BY v.ID
            ORDER BY c.DATA_INICIO_CUSTO DESC
        ) AS RN
    FROM vendas v
    JOIN custos c
        ON v.ID_PRODUCT = c.PRODUCT_ID
       AND c.DATA_INICIO_CUSTO <= v.DATA_VENDA
),

base AS (
    SELECT
        vc.ID,
        vc.ID_PRODUCT,
        vc.PRODUCT_NAME,
        vc.CATEGORY,
        vc.RECEITA_TOTAL_BRL,
        (vc.QTD * vc.USD_PRICE * cb.cotacao_venda) AS CUSTO_TOTAL_BRL
    FROM venda_custo vc
    JOIN cambio cb
        ON vc.DATA_VENDA = cb.DATA_CAMBIO
    WHERE vc.RN = 1
),

prejuizo_transacoes AS (
    SELECT
        ID_PRODUCT,
        PRODUCT_NAME,
        CATEGORY,
        RECEITA_TOTAL_BRL,
        CASE
            WHEN RECEITA_TOTAL_BRL < CUSTO_TOTAL_BRL THEN CUSTO_TOTAL_BRL - RECEITA_TOTAL_BRL
            ELSE 0
        END AS PREJUIZO_BRL
    FROM base
)

SELECT
    ID_PRODUCT,
    PRODUCT_NAME,
    CATEGORY,
    SUM(RECEITA_TOTAL_BRL) AS RECEITA_TOTAL_BRL,
    SUM(PREJUIZO_BRL) AS PREJUIZO_TOTAL_BRL,
    CASE
        WHEN SUM(RECEITA_TOTAL_BRL) = 0 THEN 0
        ELSE SUM(PREJUIZO_BRL) / SUM(RECEITA_TOTAL_BRL)
    END AS PERCENTUAL_PERDA
FROM prejuizo_transacoes
GROUP BY ID_PRODUCT, PRODUCT_NAME, CATEGORY
ORDER BY PREJUIZO_TOTAL_BRL DESC;

-- TAREFA 2 - GERAR O GRAFICO
SELECT
    PRODUCT_NAME AS "Produto",
    ROUND(PREJUIZO_TOTAL_BRL, 2) AS "Prejuízo (R$)"
FROM LH_NAUTICALS.QUESTAO4.VW_PREJUIZO_PRODUTO
WHERE PREJUIZO_TOTAL_BRL > 0
ORDER BY PREJUIZO_TOTAL_BRL DESC
LIMIT 10;

-- Qual é o id_product com maior % de perda?
SELECT
    ID_PRODUCT,
    PRODUCT_NAME,
    PERCENTUAL_PERDA
FROM LH_NAUTICALS.QUESTAO4.VW_PREJUIZO_PRODUTO
WHERE PERCENTUAL_PERDA > 0
ORDER BY PERCENTUAL_PERDA DESC
LIMIT 1;